"""build_custom_mixed_timeseries.py

Builds and visualises an oracle ensemble from three existing runs, one per
precipitation band.

For each test timestep the "mixed" prediction is chosen based on the REAL
value (y_true), making this an oracle analysis that shows the upper bound of
what a segment-specialised ensemble can achieve.

  - y_true ∈ [0, THRESHOLD_LOW)   → prediction from RUN_LOW
  - y_true ∈ [THRESHOLD_LOW, THRESHOLD_HIGH) → prediction from RUN_MID
  - y_true ≥ THRESHOLD_HIGH        → prediction from RUN_HIGH

This script does NOT retrain anything; it only reads existing NPZ artifacts
saved to GLOBAL_DEBUG_ERA5/predictions/ during the sweep.

Configuration
-------------
Edit the USER CONFIGURATION block below.
"""

import re
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

from src.config.paths import PROJECT_ROOT
from src.evaluation.metrics import mae, kge

_DATE_RANGE_RE = re.compile(r"(\d{4}-\d{2}-\d{2})-(\d{4}-\d{2}-\d{2})")


# =============================================================================
# USER CONFIGURATION
# =============================================================================

STATION_NAME = "PORTO ALEGRE - JARDIM BOTANICO"

# One run_name per band.  Use the folder name under runs/ (without station prefix).
# Tip: pick from ranking_mae_*/ranking_kge_* CSVs generated by filter_best_results.py.
RUN_LOW_NAME  = "lstm_daily_2017-01-01-2020-12-31_ts7_h1_lossquantile_0.6_scalerTrue"   # 0–10 mm
RUN_MID_NAME  = "lstm_daily_2017-01-01-2020-12-31_ts5_h2_lossquantile_0.9_scalerTrue"  # 10–30 mm
RUN_HIGH_NAME = "lstm_daily_2017-01-01-2020-12-31_ts20_h1_lossquantile_0.9_scalerTrue"  # 30+ mm

# Band thresholds (mm) applied to y_true
THRESHOLD_LOW_MM  = 10.0
THRESHOLD_HIGH_MM = 30.0

# Output figure name (saved next to runs/)
OUTPUT_FIGURE_NAME = "custom_mixed_timeseries.png"


# =============================================================================
# IMPLEMENTATION
# =============================================================================

GLOBAL_DEBUG_DIR = PROJECT_ROOT / "runs" / "GLOBAL_DEBUG_ERA5"
RUNS_ROOT        = PROJECT_ROOT / "runs"


# ---------------------------------------------------------------------------
# Loading
# ---------------------------------------------------------------------------

def _extract_dates(data) -> np.ndarray | None:
    """Return dates array from an NPZ data dict, or None if not present."""
    if "dates" in data:
        return data["dates"].astype(str)
    return None


def _reconstruct_dates(run_name: str, n: int) -> np.ndarray | None:
    """Reconstruct daily test dates from the run name.

    The last label of the sliding-window series always coincides with the
    last day of the dataset (regardless of timestep / horizon), so the
    test date range is simply the ``n`` days ending on ``end_date``.
    """
    m = _DATE_RANGE_RE.search(run_name)
    if not m:
        return None
    end_date = pd.to_datetime(m.group(2))
    return (
        pd.date_range(end=end_date, periods=n, freq="D")
        .strftime("%Y-%m-%d")
        .to_numpy()
    )


def _load_from_global_debug(station: str, run_name: str):
    """Load y_true/y_pred/dates from GLOBAL_DEBUG_ERA5/predictions/."""
    preds_dir = GLOBAL_DEBUG_DIR / "predictions"
    file_prefix = f"{station}_{run_name}"
    npz_path = preds_dir / f"{file_prefix}_test_predictions.npz"

    if npz_path.exists():
        data = np.load(npz_path, allow_pickle=True)
        return (
            data["y_true"].astype(float).flatten(),
            data["y_pred"].astype(float).flatten(),
            _extract_dates(data),
        )
    return None


def _load_from_run_dir(station: str, run_name: str):
    """Fallback: search inside the per-run directory for a matching NPZ."""
    run_dir = RUNS_ROOT / run_name
    if not run_dir.exists():
        return None

    file_prefix = f"{station}_{run_name}"

    # standard output_mode: runs/<run>/locations/<station>/predictions/
    candidate = run_dir / "locations" / station / "predictions" / f"{file_prefix}_test_predictions.npz"
    if candidate.exists():
        data = np.load(candidate, allow_pickle=True)
        return (
            data["y_true"].astype(float).flatten(),
            data["y_pred"].astype(float).flatten(),
            _extract_dates(data),
        )

    # debug output_mode: runs/<run>/debug_outputs/predictions/
    for npz in (run_dir / "debug_outputs" / "predictions").glob(f"{file_prefix}*_test_predictions.npz") if (run_dir / "debug_outputs" / "predictions").exists() else []:
        data = np.load(npz, allow_pickle=True)
        return (
            data["y_true"].astype(float).flatten(),
            data["y_pred"].astype(float).flatten(),
            _extract_dates(data),
        )

    return None


def load_predictions(station: str, run_name: str):
    result = _load_from_global_debug(station, run_name)
    if result is None:
        result = _load_from_run_dir(station, run_name)

    if result is None:
        raise FileNotFoundError(
            f"No predictions NPZ found for station='{station}', run='{run_name}'.\n"
            f"Searched in:\n"
            f"  {GLOBAL_DEBUG_DIR}/predictions/{station}_{run_name}_test_predictions.npz\n"
            f"  {RUNS_ROOT}/{run_name}/locations/{station}/predictions/\n"
            "Make sure the sweep has run and global_debug_dir is set."
        )

    y_true, y_pred, dates = result
    # Fallback: reconstruct dates from run name when NPZ was saved without them
    if dates is None:
        dates = _reconstruct_dates(run_name, len(y_true))
    return y_true, y_pred, dates


# ---------------------------------------------------------------------------
# Metrics helpers (segment-level)
# ---------------------------------------------------------------------------

def _segment_mask(y_true, low, high=None):
    if high is None:
        return y_true >= low
    return (y_true >= low) & (y_true < high)


def _report_metrics(label, yt, yp):
    if len(yt) == 0:
        print(f"  {label}: no samples")
        return
    mae_val  = float(np.mean(np.abs(yt - yp)))
    kge_val  = kge(yt, yp)
    print(f"  {label:30s}  n={len(yt):5d}  MAE={mae_val:.3f} mm  KGE={kge_val:.3f}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def build_custom_mixed_timeseries():
    # ------------------------------------------------------------------
    # Load
    # ------------------------------------------------------------------
    print(f"Loading predictions for station: {STATION_NAME}\n")
    y_true_low,  y_pred_low,  dates_low  = load_predictions(STATION_NAME, RUN_LOW_NAME)
    y_true_mid,  y_pred_mid,  dates_mid  = load_predictions(STATION_NAME, RUN_MID_NAME)
    y_true_high, y_pred_high, dates_high = load_predictions(STATION_NAME, RUN_HIGH_NAME)

    # ------------------------------------------------------------------
    # Alignment check
    # ------------------------------------------------------------------
    lengths = {"low": len(y_true_low), "mid": len(y_true_mid), "high": len(y_true_high)}
    print("Test set lengths:", lengths)

    if not (np.array_equal(y_true_low, y_true_mid) and np.array_equal(y_true_low, y_true_high)):
        print(
            "[WARN] y_true arrays differ across runs — the three runs were likely trained "
            "with different timestep/horizon settings, shifting the test window.\n"
            "       The series will be aligned to the shortest common length."
        )

    n = min(lengths.values())
    if n < max(lengths.values()):
        print(f"       Clipping all series to {n} samples.\n")

    y_true      = y_true_low[:n]
    y_pred_low  = y_pred_low[:n]
    y_pred_mid  = y_pred_mid[:n]
    y_pred_high = y_pred_high[:n]

    # Use the dates from the LOW run as the reference x-axis (after clipping)
    dates = dates_low[:n] if dates_low is not None else None
    x = pd.to_datetime(dates) if dates is not None else np.arange(n)

    # ------------------------------------------------------------------
    # Oracle ensemble: mix based on y_true bands
    # ------------------------------------------------------------------
    low  = THRESHOLD_LOW_MM
    high = THRESHOLD_HIGH_MM

    mask_low  = _segment_mask(y_true, 0,    low)
    mask_mid  = _segment_mask(y_true, low,  high)
    mask_high = _segment_mask(y_true, high)

    y_mixed = np.empty(n, dtype=float)
    y_mixed[mask_low]  = y_pred_low[mask_low]
    y_mixed[mask_mid]  = y_pred_mid[mask_mid]
    y_mixed[mask_high] = y_pred_high[mask_high]

    print(f"Band distribution  (thresholds: low={low} mm, high={high} mm):")
    print(f"  0–{low} mm  : {mask_low.sum():5d} samples ({100*mask_low.mean():.1f}%)")
    print(f"  {low}–{high} mm : {mask_mid.sum():5d} samples ({100*mask_mid.mean():.1f}%)")
    print(f"  ≥{high} mm  : {mask_high.sum():5d} samples ({100*mask_high.mean():.1f}%)\n")

    # ------------------------------------------------------------------
    # Metrics
    # ------------------------------------------------------------------
    print("Metrics per band and for each individual model:")
    _report_metrics(f"LOW  run  (0–{low} mm)",  y_true[mask_low],  y_pred_low[mask_low])
    _report_metrics(f"MID  run  ({low}–{high} mm)", y_true[mask_mid],  y_pred_mid[mask_mid])
    _report_metrics(f"HIGH run  (≥{high} mm)",  y_true[mask_high], y_pred_high[mask_high])
    print()
    print("Mixed model:")
    _report_metrics(f"  0–{low} mm (from LOW run)",     y_true[mask_low],  y_mixed[mask_low])
    _report_metrics(f"  {low}–{high} mm (from MID run)", y_true[mask_mid],  y_mixed[mask_mid])
    _report_metrics(f"  ≥{high} mm (from HIGH run)",    y_true[mask_high], y_mixed[mask_high])
    _report_metrics("  Overall mixed",                   y_true,            y_mixed)

    # ------------------------------------------------------------------
    # MAE summary
    # ------------------------------------------------------------------
    mae_low_band  = float(np.mean(np.abs(y_true[mask_low]  - y_mixed[mask_low])))  if mask_low.any()  else float("nan")
    mae_mid_band  = float(np.mean(np.abs(y_true[mask_mid]  - y_mixed[mask_mid])))  if mask_mid.any()  else float("nan")
    mae_high_band = float(np.mean(np.abs(y_true[mask_high] - y_mixed[mask_high]))) if mask_high.any() else float("nan")
    mae_total     = float(np.mean(np.abs(y_true - y_mixed)))

    print(f"\n{'─'*44}")
    print(f"  MAE SUMMARY")
    print(f"{'─'*44}")
    print(f"  0–{low} mm band   : {mae_low_band:.3f} mm")
    print(f"  {low}–{high} mm band  : {mae_mid_band:.3f} mm")
    print(f"  ≥{high} mm band   : {mae_high_band:.3f} mm")
    print(f"  {'─'*30}")
    print(f"  Total (mixed)    : {mae_total:.3f} mm")
    print(f"{'─'*44}\n")

    # ------------------------------------------------------------------
    # Plot — two versions (dashed / solid prediction)
    # ------------------------------------------------------------------
    title = f"Mixed Configuration — {STATION_NAME}  (bands: 0–{low} / {low}–{high} / ≥{high} mm)"

    for linestyle, suffix in [("--", "dashed"), ("-", "solid")]:
        fig, ax = plt.subplots(figsize=(14, 5))

        ax.plot(x, y_true,  label="Real (ERA5)", linewidth=2, color="steelblue")
        ax.plot(x, y_mixed, label="Mixed prediction", linewidth=2,
                linestyle=linestyle, color="tomato")

        ax.set_title(title, fontsize=10, weight="bold")
        ax.set_ylabel("Precipitation (mm)")
        ax.legend()
        ax.grid(True, alpha=0.3)

        # Date formatting when real dates are available
        if dates is not None:
            ax.xaxis.set_major_locator(mdates.MonthLocator(interval=2))
            ax.xaxis.set_major_formatter(mdates.DateFormatter("%b %Y"))
            fig.autofmt_xdate(rotation=30, ha="right")
        else:
            ax.set_xlabel("Time step")

        fig.tight_layout()

        stem = OUTPUT_FIGURE_NAME.replace(".png", f"_{suffix}.png")
        out_path = RUNS_ROOT / stem
        fig.savefig(out_path, dpi=300, bbox_inches="tight")
        plt.close(fig)
        print(f"\nPlot saved: {out_path}")


if __name__ == "__main__":
    build_custom_mixed_timeseries()
